apiVersion: apps/v1
kind: deployment
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: techtrends
      spec:
        containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          name: techtrends