kind: Application
metadata:
  name: techtrends
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
    project: default
    source:
      helm:
        valueFiles:
        - values-staging.yaml
      path: 