apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: techtrends
  name: techtrends
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: techtrends
    spec:
      containers:
      - image: https://hub.docker.com/repository/docker/solondungu/techtrends:latest
        name: techtrends
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3111
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3111
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
          - name: liveness-port
            containerPort: 3111
        resources: {}
status: {}
