namespace:
  name: prod

service:
  port: 7111

containers:
  imagePullPolicy: Always

replicaCount: 5

resources:
  requests:
    memory: 128Mi
    cpu: 350m
  limits:
    memory: 250Mi
    cpu: 500m